### ISSUE TITLE
Deployment failed

### ISSUE THREAD

**Issue by kaby76** [Microsoft/BikeSharing360_BackendServices#3]
When I followed the directions for deployment of this project, I got an error in reading the njscsproj file. I have Node.JS installed, but the requirement should be to install Node.js Tools 1.2 for Visual Studio 2015 (https://marketplace.visualstudio.com/items?itemName=NodejsToolsforVisualStudio.NodejsTools12forVisualStudio2015). Not to be too picky, but it would be good to have all the readme.md's follow a template, listing out the requirements.

When deploying, I get the error message "15:31:38 - PowerShell deployment script c:\users\ken\documents\bikesharing360_backendservices\src\bikesharing.services.deploy\Scripts\Deploy-AzureResourceGroup.ps1 is missing.
15:31:38 - Deploying template using PowerShell script failed.". The file is in the location .../bikesharing.services.deploy/; there is no scripts/ subdirectory. I am using the master branch, last checkin at 13 Dec 3:03.

**Comment by eiximenis** [comment]
Hi @kaby76!
I updated the readme.md with the NodeJS tools pre-requisite and other interesting info.
Thanks

Regarding the issue that you found, how do you start the deploy? Its a weird message because no Scripts folder exists...

**Comment by kaby76** [comment]
I just followed the directions you provided. Right-click on the project -> New -> Deploy. It appears, though, that Azure SDK isn't installed. Found the link from Google search of "Download Azure SDK .NET (2.9.6)". It would be nice to add that link in the prerequisites. Thanks for the updated readme! Will give that a try. --Ken

**Comment by kaby76** [comment]
Much better. Installing Azure helped, duh. Thanks!!
