### ISSUE TITLE
SQL Server Deployment Fails

### ISSUE THREAD

**Issue by mohamedsaif** [Microsoft/BikeSharing360_BackendServices#8]
Hi, 
When I tried to deploy the backend deployment project it fails at the SQL Server deployment step with (Bad Request) on the Azure deployment log.
 The following status in the Azure failed deployment log:

{
  "code": "45122",
  "message": "''",
  "target": null,
  "details": [
    {
      "code": "45122",
      "message": "''",
      "target": null,
      "severity": "16"
    }
  ],
  "innererror": []
}

**Comment by eiximenis** [comment]
Hi!
This is an issue that happens to some Azure zones (i am not sure why).

Test in with another resource group zone  (i. e. WEST US 2 worked for me today).
